### ISSUE TITLE
`isAuthenticated` always return true if request type is not JSON

### ISSUE THREAD

**Issue by Varkh** [vlavrynovych/angular-spa-auth#14]
Conditions:
`isAuthenticated` endpoint response with `content-type:text/plain`, body `false`

Result:
User is authenticated(at least User refresh called)

**Comment by vlavrynovych** [comment]
Yeap, you need to use JSON response for correct work, but we definitely should add check for string values

**Comment by vlavrynovych** [comment]
Who wanna fix? ))
